// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/builder/document.proto

package builder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 文档合并的请求
type DocumentMergeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label                []string `protobuf:"bytes,2,rep,name=label,proto3" json:"label,omitempty"`
	Text                 []string `protobuf:"bytes,3,rep,name=text,proto3" json:"text,omitempty"`
	Format               string   `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentMergeRequest) Reset()         { *m = DocumentMergeRequest{} }
func (m *DocumentMergeRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentMergeRequest) ProtoMessage()    {}
func (*DocumentMergeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2565ead467a476, []int{0}
}

func (m *DocumentMergeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentMergeRequest.Unmarshal(m, b)
}
func (m *DocumentMergeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentMergeRequest.Marshal(b, m, deterministic)
}
func (m *DocumentMergeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentMergeRequest.Merge(m, src)
}
func (m *DocumentMergeRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentMergeRequest.Size(m)
}
func (m *DocumentMergeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentMergeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentMergeRequest proto.InternalMessageInfo

func (m *DocumentMergeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DocumentMergeRequest) GetLabel() []string {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *DocumentMergeRequest) GetText() []string {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *DocumentMergeRequest) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type DocumentListResponse struct {
	Status               *Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Entity               []*DocumentEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DocumentListResponse) Reset()         { *m = DocumentListResponse{} }
func (m *DocumentListResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentListResponse) ProtoMessage()    {}
func (*DocumentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db2565ead467a476, []int{1}
}

func (m *DocumentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentListResponse.Unmarshal(m, b)
}
func (m *DocumentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentListResponse.Marshal(b, m, deterministic)
}
func (m *DocumentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentListResponse.Merge(m, src)
}
func (m *DocumentListResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentListResponse.Size(m)
}
func (m *DocumentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentListResponse proto.InternalMessageInfo

func (m *DocumentListResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DocumentListResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DocumentListResponse) GetEntity() []*DocumentEntity {
	if m != nil {
		return m.Entity
	}
	return nil
}

func init() {
	proto.RegisterType((*DocumentMergeRequest)(nil), "builder.DocumentMergeRequest")
	proto.RegisterType((*DocumentListResponse)(nil), "builder.DocumentListResponse")
}

func init() {
	proto.RegisterFile("proto/builder/document.proto", fileDescriptor_db2565ead467a476)
}

var fileDescriptor_db2565ead467a476 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0x2e, 0x42, 0xd1, 0x6e, 0x0f, 0x26, 0x13, 0x52, 0x09, 0xd1, 0xa4, 0xe1, 0x22, 0x27, 0x48,
	0xf0, 0x6c, 0x62, 0x8c, 0xde, 0xf4, 0xb2, 0x3e, 0xc1, 0x22, 0xa3, 0x12, 0x81, 0xad, 0xec, 0x90,
	0xe8, 0x0b, 0x78, 0xf1, 0xa5, 0x0d, 0xc3, 0x82, 0x35, 0xbd, 0xcd, 0x7c, 0x3f, 0xcc, 0xf7, 0xb1,
	0xe2, 0x7c, 0xd7, 0x69, 0xd2, 0x59, 0xd1, 0x57, 0x75, 0x89, 0x5d, 0x56, 0xea, 0xe7, 0xbe, 0xc1,
	0x96, 0x52, 0x86, 0xe1, 0xd8, 0xe2, 0x51, 0xf4, 0x5f, 0x66, 0xde, 0x54, 0x87, 0xe5, 0x28, 0x8a,
	0x6b, 0x11, 0xdc, 0x59, 0xdb, 0x23, 0x76, 0xaf, 0x28, 0xf1, 0xa3, 0x47, 0x43, 0x00, 0xc2, 0x6b,
	0x55, 0x83, 0xa1, 0xb3, 0x75, 0x92, 0x95, 0xe4, 0x19, 0x02, 0xb1, 0xac, 0x55, 0x81, 0x75, 0x78,
	0xb4, 0x75, 0x93, 0x95, 0x1c, 0x97, 0x41, 0x49, 0xf8, 0x49, 0xa1, 0xcb, 0x20, 0xcf, 0xb0, 0x11,
	0xfe, 0x8b, 0xee, 0x1a, 0x45, 0xa1, 0xc7, 0x7e, 0xbb, 0xc5, 0xdf, 0xce, 0xdf, 0xb9, 0x87, 0xca,
	0x90, 0x44, 0xb3, 0xd3, 0xad, 0x41, 0xb8, 0x14, 0xbe, 0x21, 0x45, 0xbd, 0xe1, 0x83, 0xeb, 0xfc,
	0x34, 0xb5, 0x69, 0xd3, 0x27, 0x86, 0xa5, 0xa5, 0x87, 0x0c, 0xa4, 0x49, 0x0d, 0x19, 0x9c, 0xc4,
	0x95, 0xe3, 0x02, 0x99, 0xf0, 0xb1, 0xa5, 0x8a, 0xbe, 0x38, 0xc5, 0x3a, 0x3f, 0x9b, 0xed, 0xd3,
	0xb5, 0x7b, 0xa6, 0xa5, 0x95, 0xe5, 0x3f, 0x8e, 0x38, 0x99, 0x28, 0xb8, 0x11, 0x4b, 0xee, 0x0e,
	0x17, 0x07, 0xb6, 0xfd, 0x7f, 0x12, 0x6d, 0x66, 0xfa, 0xb6, 0x56, 0xed, 0xfb, 0x14, 0x3e, 0x5e,
	0xc0, 0xb5, 0xf0, 0x86, 0x3a, 0x10, 0xcc, 0x8a, 0xb1, 0xdd, 0xe8, 0x3b, 0xfc, 0xec, 0x7e, 0xf7,
	0x78, 0x51, 0xf8, 0xfc, 0x16, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0xdd, 0x5a, 0xa7,
	0xd0, 0x01, 0x00, 0x00,
}
