// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/builder/shared.proto

package builder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_019f0c46314829b4, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_019f0c46314829b4, []int{1}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 文档实体
type DocumentEntity struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Label                []string `protobuf:"bytes,3,rep,name=label,proto3" json:"label,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentEntity) Reset()         { *m = DocumentEntity{} }
func (m *DocumentEntity) String() string { return proto.CompactTextString(m) }
func (*DocumentEntity) ProtoMessage()    {}
func (*DocumentEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_019f0c46314829b4, []int{2}
}

func (m *DocumentEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentEntity.Unmarshal(m, b)
}
func (m *DocumentEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentEntity.Marshal(b, m, deterministic)
}
func (m *DocumentEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentEntity.Merge(m, src)
}
func (m *DocumentEntity) XXX_Size() int {
	return xxx_messageInfo_DocumentEntity.Size(m)
}
func (m *DocumentEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentEntity.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentEntity proto.InternalMessageInfo

func (m *DocumentEntity) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DocumentEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DocumentEntity) GetLabel() []string {
	if m != nil {
		return m.Label
	}
	return nil
}

func (m *DocumentEntity) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *DocumentEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// 列举的请求
type ListRequest struct {
	Offset               int64             `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64             `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Filter               map[string]string `protobuf:"bytes,3,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_019f0c46314829b4, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ListRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "builder.Status")
	proto.RegisterType((*BlankResponse)(nil), "builder.BlankResponse")
	proto.RegisterType((*DocumentEntity)(nil), "builder.DocumentEntity")
	proto.RegisterType((*ListRequest)(nil), "builder.ListRequest")
	proto.RegisterMapType((map[string]string)(nil), "builder.ListRequest.FilterEntry")
}

func init() {
	proto.RegisterFile("proto/builder/shared.proto", fileDescriptor_019f0c46314829b4)
}

var fileDescriptor_019f0c46314829b4 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xc1, 0x4e, 0xeb, 0x30,
	0x10, 0x94, 0x9b, 0xd7, 0x54, 0xd9, 0xe8, 0x01, 0xb2, 0x10, 0x8a, 0x2a, 0x0e, 0x51, 0x2e, 0xe4,
	0x94, 0x4a, 0x45, 0x42, 0x85, 0x1b, 0x88, 0x72, 0xe2, 0x64, 0xbe, 0xc0, 0x6d, 0xb6, 0x10, 0x35,
	0xb5, 0x4b, 0xbc, 0x46, 0xf4, 0xc6, 0x27, 0xf1, 0x89, 0xc8, 0x8e, 0x03, 0xbd, 0xcd, 0x4c, 0x26,
	0x33, 0x3b, 0x32, 0x4c, 0xf7, 0x9d, 0x26, 0x3d, 0x5b, 0xd9, 0xa6, 0xad, 0xb1, 0x9b, 0x99, 0x37,
	0xd9, 0x61, 0x5d, 0x79, 0x91, 0x4f, 0x82, 0x5a, 0xdc, 0x40, 0xfc, 0x42, 0x92, 0xac, 0xe1, 0x1c,
	0xfe, 0xad, 0x75, 0x8d, 0x19, 0xcb, 0x59, 0x39, 0x16, 0x1e, 0xf3, 0x0c, 0x26, 0x3b, 0x34, 0x46,
	0xbe, 0x62, 0x36, 0xca, 0x59, 0x99, 0x88, 0x81, 0x16, 0x0b, 0xf8, 0xff, 0xd0, 0x4a, 0xb5, 0x15,
	0x68, 0xf6, 0x5a, 0x19, 0xe4, 0x57, 0x10, 0x1b, 0x1f, 0xe4, 0x03, 0xd2, 0xf9, 0x69, 0x15, 0x2a,
	0xaa, 0x3e, 0x5f, 0x84, 0xcf, 0xc5, 0x17, 0x83, 0x93, 0x47, 0xbd, 0xb6, 0x3b, 0x54, 0xb4, 0x54,
	0xd4, 0xd0, 0xc1, 0x55, 0x5b, 0xdb, 0xd4, 0xfe, 0xcf, 0x44, 0x78, 0xec, 0x34, 0x25, 0x77, 0x43,
	0xaf, 0xc7, 0xfc, 0x1c, 0xc6, 0xad, 0x5c, 0x61, 0x9b, 0x45, 0x79, 0x54, 0x26, 0xa2, 0x27, 0xce,
	0x49, 0xf8, 0x49, 0xd9, 0xb8, 0x77, 0x3a, 0xcc, 0x2f, 0x21, 0xb1, 0xfb, 0x5a, 0x12, 0xd6, 0xf7,
	0x94, 0x4d, 0x72, 0x56, 0x46, 0xe2, 0x4f, 0x28, 0xbe, 0x19, 0xa4, 0xcf, 0x8d, 0x21, 0x81, 0xef,
	0x16, 0x0d, 0xf1, 0x0b, 0x88, 0xf5, 0x66, 0x63, 0x90, 0xfc, 0x05, 0x91, 0x08, 0xcc, 0xf5, 0xad,
	0xb5, 0x55, 0xe4, 0x8f, 0x88, 0x44, 0x4f, 0xf8, 0x02, 0xe2, 0x4d, 0xd3, 0x12, 0x76, 0xfe, 0x8c,
	0x74, 0x9e, 0xff, 0x2e, 0x3d, 0xca, 0xac, 0x9e, 0xbc, 0x65, 0xa9, 0xa8, 0x3b, 0x88, 0xe0, 0x9f,
	0xde, 0x42, 0x7a, 0x24, 0xf3, 0x33, 0x88, 0xb6, 0x78, 0x08, 0xab, 0x1d, 0x74, 0x85, 0x1f, 0xb2,
	0xb5, 0xc3, 0xea, 0x9e, 0xdc, 0x8d, 0x16, 0x6c, 0x15, 0xfb, 0x77, 0xbb, 0xfe, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x19, 0xf4, 0x4f, 0x28, 0xd5, 0x01, 0x00, 0x00,
}
